### ISSUE TITLE
Automatic Inclusion of POA20 Token in Default Addr?

### ISSUE THREAD

**Issue by jflowers1974** [poanetwork/metamask-extension#113]
Just wondering if it would be possible that the information for POA20 is, by default, already present for the default/first account made.

I figure that this would help new comers - as they may not have the skills to search and insert this contract address (0x6758b7d441a9739b98552b373703d8d3d14f9e62)

Also, I noticed that after adding POA20 - the icon isn't POA branded. Not a big deal, but would be nice. 

![screen shot 2018-09-07 at 11 23 00 pm](https://user-images.githubusercontent.com/4926929/45251079-08d97200-b2f5-11e8-998f-e423aac4573c.png)

**Comment by vbaranov** [comment]
@jflowers1974 The default addition of POA20 token will lead to additional data requests to get the token balance for those who don't want to track this token. In order of simplification for newcomers, I'd suggest to implement some kind of token's search functionality by the name of the token and to add POA20 to the list of searchable tokens. It would be more generic, I think.

>Also, I noticed that after adding POA20 - the icon isn't POA branded. Not a big deal, but would be nice.

Thanks for noting that. I've created a [PR to add POA20 token image to the corresponding repo](https://github.com/MetaMask/eth-contract-metadata/pull/160).
