### ISSUE TITLE
Support POA network

### ISSUE THREAD

**Issue by pablofullana** [poanetwork/metamask-extension#2]
**Goals:**
- [ ] Make POA default network
- [ ]  Open txs in [poaexplorer](poaexplorer.com)

**References:**
- [Previous fork repository](https://github.com/oraclesorg/metamask-plugin)
- Relevant commits:
  - [1572538](1572538b269ff678069cbed9a6b70658db5adeaf)
  - [1e9ddef](1e9ddef9c4f88eef47aa395bdafffe04fcb0d745)
  - [6f6cca9](6f6cca99758772795f2e8dafa3c53fa82aa4bbbc)
- [Sparrow browser extension for Ubiq](https://github.com/ubiq/sparrow-extension)

**Comment by vbaranov** [comment]
The guide on how to add a new network:
https://github.com/MetaMask/metamask-extension/blob/develop/docs/adding-new-networks.md
