### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by kumavis** [poanetwork/metamask-extension#21]
Please replace the logo with an original one

thanks

**Comment by igorbarinov** [comment]
Hi, @kumavis  sorry about that. The violet fox icon was a temporary solution before rebranding of the fork. We will replace the icon with a new set not related to MM branding. ETA is today.

We have a goal to make NW working with MM installed https://github.com/poanetwork/metamask-extension/issues/1 so it will be confusion with MM if we use the same icon. Despite all the great work what you've we done for the client, we disagree with the governance of MM and would like to keep a distance from it in NW fork. E.g. of censorships:
- POA https://github.com/MetaMask/metamask-extension/pull/2815
- EOS Classic https://github.com/MetaMask/metamask-extension/pull/4816
- RSK https://github.com/MetaMask/metamask-extension/issues/3096
etc

**Comment by vbaranov** [comment]
@kumavis @igorbarinov logo is changed for Nifty Wallet in the current repo. Will be implemented with the next release.

**Comment by radamosch** [comment]
hi @vbaranov  do you know when this will be released ? thx

**Comment by vbaranov** [comment]
@radamosch NW@4.8.2 is released.
