### ISSUE TITLE
Support Sokol network

### ISSUE THREAD

**Issue by pablofullana** [poanetwork/metamask-extension#3]
Add support for Sokol network

**Comment by igorbarinov** [comment]
Explorer for Sokol is https://sokol.poaexplorer.com

**Comment by vbaranov** [comment]
The guide on how to add a new network:
https://github.com/MetaMask/metamask-extension/blob/develop/docs/adding-new-networks.md

**Comment by vbaranov** [comment]
Link to Sokol faucet could be added: https://faucet-sokol.herokuapp.com/
