### ISSUE TITLE
Replace design assets/links references to MM

### ISSUE THREAD

**Issue by pablofullana** [poanetwork/metamask-extension#5]
Review the whole project and update assets, links, strings and anything that may refer to MM

**Comment by igorbarinov** [comment]
- replace icons to https://www.dropbox.com/sh/f808p8o7eln1x8o/AACn8Znq5r0CdZHKUzg4JgB1a?dl=0
- replace name to Nifty Wallet

**Comment by vbaranov** [comment]
@igorbarinov 

There are missing icons:
- 64 × 64
- 512 x 512

Please ask to add them too.
