### ISSUE TITLE
"Add token" function data is shared between all networks

### ISSUE THREAD

**Issue by clbrge** [poanetwork/metamask-extension#65]
Briefly describe the issue you've encountered
  *  Expected Behavior
If you add a custom token on a specific network (Ropsten) with a specific address, there is no reason that the same address described the same token on another network.

  *  Actual Behavior
If you add a token for Ropsten (eg) you get it listed when you switch to POA. It's even more confusing if you have tokens with the same name (and different network) you want to use in parallel.

solution : "Add token" should store data per network and not globally.

Version tested Nifty 4.8.2
Same problem in MetaMask 4.8.0 (what's your policy about upstream bug ?)

**Comment by igorbarinov** [comment]
@clbrge  good catch, it's one of the annoying things we'd like to fix from MM experience.
