### ISSUE TITLE
Wrong balance displaying on many accounts

### ISSUE THREAD

**Issue by acravenho** [poanetwork/metamask-extension#74]
I'm seeing the wrong balance display on several accounts for the Nifty Wallet. I've provided pictures below showing a web3.eth.getBalance call along with the associated wallet. 

<img width="1050" alt="screen shot 2018-08-09 at 10 00 46 pm" src="https://user-images.githubusercontent.com/17620007/43934981-dacfebd2-9c1f-11e8-8855-831134367339.png">

<img width="1137" alt="screen shot 2018-08-09 at 9 59 39 pm" src="https://user-images.githubusercontent.com/17620007/43934990-e146fc3a-9c1f-11e8-8f15-b80c0caf474b.png">

**Comment by vbaranov** [comment]
@acravenho Is this inconsistency found only for POA network?

**Comment by acravenho** [comment]
@vbaranov This might be a far edge case. I just solved the issue by deactivating the extension and reactivating it. It seems to be updating just fine now.

What I believe caused the issue was interacting with my desktop computer and then coming back to my laptop. Since Chrome shares data between the same logged in account including extensions I might have been receiving stale data. 

I believe this issue can be closed. Sorry for the inconvenience. I'll let you know if I see this issue occur more frequently.
